#!/usr/bin/env python3
"""
Infra Ops Center — Initial Setup Script

Generates:
  - Admin username & bcrypt password hash
  - Fernet encryption key for device storage
  - .env file with all required configuration

Usage:
    python setup_env.py
"""

import os
import sys
import secrets


def main():
    print("=" * 60)
    print("🛡️  Infra Ops Center with AI — Initial Setup")
    print("=" * 60)
    print()

    env_path = os.path.join(os.path.dirname(__file__), ".env")

    if os.path.exists(env_path):
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != "y":
            print("Aborted.")
            return

    # --- Admin credentials ---
    print("\n📋 Admin Account Setup")
    print("-" * 40)

    username = input("Admin username (default: admin): ").strip() or "admin"

    while True:
        password = input("Admin password (min 6 chars): ").strip()
        if len(password) >= 6:
            break
        print("❌ Password must be at least 6 characters.")

    # Generate bcrypt hash
    try:
        import bcrypt
    except ImportError:
        print("\n⚠️  bcrypt not installed. Installing...")
        os.system(f"{sys.executable} -m pip install bcrypt -q")
        import bcrypt

    password_hash = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
    print(f"✅ Password hash generated")

    # --- Fernet key ---
    print("\n🔐 Device Encryption Key")
    print("-" * 40)

    try:
        from cryptography.fernet import Fernet
    except ImportError:
        print("⚠️  cryptography not installed. Installing...")
        os.system(f"{sys.executable} -m pip install cryptography -q")
        from cryptography.fernet import Fernet

    fernet_key = Fernet.generate_key().decode("utf-8")
    print(f"✅ Fernet encryption key generated")

    # --- AI Provider ---
    print("\n🤖 AI Provider Configuration")
    print("-" * 40)
    print("1. Direct API (Anthropic/OpenAI/Gemini)")
    print("2. onPrem LLM Sentinel proxy")

    mode = input("Select mode (1/2, default: 1): ").strip() or "1"

    proxy_enabled = "false"
    proxy_host = "localhost"
    proxy_port = "8765"
    proxy_api_key = ""
    anthropic_key = ""
    openai_key = ""

    if mode == "2":
        proxy_enabled = "true"
        proxy_host = input("Proxy host (default: localhost): ").strip() or "localhost"
        proxy_port = input("Proxy port (default: 8765): ").strip() or "8765"
        proxy_api_key = input("Proxy API key: ").strip()
    else:
        print("\nEnter API keys (leave blank to skip):")
        anthropic_key = input("Anthropic API key: ").strip()
        openai_key = input("OpenAI API key: ").strip()

    default_provider = "anthropic" if anthropic_key else ("openai" if openai_key else "anthropic")

    # --- Write .env ---
    print("\n📝 Writing .env file...")
    print("-" * 40)

    env_content = f"""# === Infra Ops Center with AI — Configuration ===
# Generated by setup_env.py

# --- AI Provider ---
DEFAULT_PROVIDER={default_provider}
DEFAULT_MODEL=claude-sonnet-4-5
ANTHROPIC_API_KEY={anthropic_key}
OPENAI_API_KEY={openai_key}

# --- AI Proxy (onPrem LLM Sentinel) ---
PROXY_ENABLED={proxy_enabled}
PROXY_HOST={proxy_host}
PROXY_PORT={proxy_port}
PROXY_API_KEY={proxy_api_key}

# --- Authentication ---
APP_USERNAME={username}
APP_PASSWORD_HASH={password_hash}
ADMIN_USERS={username}

# --- Device Encryption ---
DEVICE_ENCRYPTION_KEY={fernet_key}

# --- SSH ---
SSH_TIMEOUT=20
SSH_EXEC_TIMEOUT=1800
SSH_OUTPUT_LIMIT=5000

# --- Agent ---
MAX_AGENT_STEPS=25

# --- RAG ---
RAG_ENABLED=true
RAG_CHUNK_SIZE=1000
RAG_TOP_K=5
"""

    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)

    print(f"✅ .env file written to: {env_path}")
    print()
    print("=" * 60)
    print("🎉 Setup complete!")
    print("=" * 60)
    print()
    print(f"  Username:  {username}")
    print(f"  Password:  {'*' * len(password)}")
    print(f"  Provider:  {default_provider}")
    print(f"  Proxy:     {'Enabled' if proxy_enabled == 'true' else 'Disabled (Direct API)'}")
    print()
    print("Start the application:")
    print("  python -m streamlit run main.py")
    print()


if __name__ == "__main__":
    main()
